# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  revision: $[counter(variables['Minor'], 1)]
  nugetVersion: '$(Major).$(Minor).$(revision)'
  nugetProjectName: 'StringLibrary'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore Solution'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Create Nuget Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/$(nugetProjectName).csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'nugetVersion'
    nobuild: true
    outputDir: '$(Build.ArtifactStagingDirectory)'
    arguments: '--configuration $(buildConfiguration) /p:PackageVersion=$(nugetVersion)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'fd280015-485a-4f2b-99a1-bee816cd1174/5773e40e-2ab3-4afb-ad24-228294ddaafd'